MyApp/Forum/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'Forum'
urlpatterns = [
        #  GET forums, POST forum
        path('', views.forum, name='forum'),

        # GET forum, DELETE forum
        path('<forum_id>', views.forum_detail, name='forum_detail'),

        # POST forum vote
        path('<forum_id>/vote', views.forum_vote, name='forum_vote'),

        # GET all comments, POST comment
        path('<forum_id>/comment', views.comment, name='comment'),

        # GET comment, DELETE comment
        path('<forum_id>/<comment_id>', views.comment_detail, name='comment_detail'),

        # POST comment vote
        path('<forum_id>/<comment_id>/vote', views.comment_vote, name='comment_vote'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

MyApp/MyApp/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('Forum/', include('Forum.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

MyApp/Forum/models.py
import datetime
import json
import math

from django.contrib import admin
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.utils.timezone import now, utc
from mptt.models import MPTTModel, TreeForeignKey
from django.db import models
from django.contrib.gis.db import models as sp_models
import random


class User(models.Model):
    name = models.CharField(max_length=24)
    biri = models.CharField(max_length=100)

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = "U" + self.scramble()
        super(User, self).save(*args, **kwargs)

    def scramble(self):
        return ''.join(random.sample(self.biri, len(self.biri)))


class VoterManager(models.Manager):
    def get_previously_voted(self, user):
        forums = []
        for vote in super().get_queryset().filter(user_id=user.id).exclude(score=0):
            forums.append(self.get_forum(vote))

        return forums

    def get_forum(self, voter):
        for forum in Forum.objects.filter(id=voter.forum_voted.id):
            return forum


class Base(models.Model):
    pub_date = models.DateTimeField(default=now, blank=True)
    text = models.CharField(max_length=10000, blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def delete_user(self):
        self.user = None
        self.text = "Deleted"

    def get_age(self):
        current_time = datetime.datetime.utcnow().replace(tzinfo=utc)
        time_since_post = current_time - self.pub_date
        days = time_since_post.days
        seconds = time_since_post.seconds

        if days >= 730:
            days = math.trunc(days / 365)
            return str(days) + " years ago"
        elif days >= 365:
            days = math.trunc(days / 365)
            return str(days) + " year ago"

        if days >= 2:
            days = days
            return str(days) + " days ago"
        elif days == 1:
            days = days
            return str(days) + " day ago"
        else:
            hours = math.trunc(seconds / 3600)
            if hours <= 0:
                minutes = math.trunc(seconds / 60)
                if minutes >= 1:
                    return str(minutes) + "m ago"
                else:
                    if seconds == 0:
                        return "now"
                    else:
                        return str(seconds) + "s ago"
            return str(hours) + "h ago"

    class Meta:
        abstract = True


class Voter(models.Model):
    forum_voted = models.ForeignKey('Forum', on_delete=models.CASCADE, blank=True, null=True,
                                    related_name='forum_voter_set')
    comment_voted = models.ForeignKey('Comment', on_delete=models.CASCADE, blank=True, null=True,
                                      related_name='comment_voter_set')

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)

    def up_vote(self):
        if self.score < 1:
            self.score = self.score + 1

    def down_vote(self):
        if self.score > -1:
            self.score = self.score - 1

    objects = models.Manager()
    voted = VoterManager()


class Forum(Base):
    slug = models.CharField(max_length=256, blank=True)

    title = models.CharField(max_length=200, blank=False)
    hashtag = models.CharField(max_length=2000, blank=True)

    score = models.ManyToManyField(Voter, blank=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True, default="default.jpg")
    embed_video = models.URLField(max_length=200, blank=True, null=True)

    latitude = sp_models.DecimalField(decimal_places=6, max_digits=9, blank=False, null=True, verbose_name='Latitude')
    longitude = sp_models.DecimalField(decimal_places=6, max_digits=9, blank=False, null=True, verbose_name='Longitude')

    # DELETE DATABASE, then comment location then migrate then uncomment
    # ADD IN LOCATION LAST COMMENT IT OUT FIRST THEN RUN MIGRATIONS
    location = sp_models.PointField(geography=True, null=True, blank=True)

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Forum, self).save(*args, **kwargs)

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.title

    def get_score(self):
        score = 0
        for vote in Voter.objects.filter(forum=self.id):
            score += vote.score
        return score

    def get_user(self):
        user = User.objects.get(id=self.user.id)
        return user

    def check_if_image_exists(self):
        if not self.image:
            return False
        else:
            return True

    def delete_user(self):
        self.user = None

    objects = models.Manager()


class Comment(MPTTModel, Base):
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    path = models.CharField(max_length=10000, blank=True)

    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)

    score = models.ManyToManyField(Voter, blank=True)

    class MPTTMeta:
        order_insertion_by = ['-pub_date']

    def get_score(self):
        score = 0
        for vote in Voter.objects.filter(comment=self.id):
            score += vote.score
        return score

    def get_user(self):
        user = User.objects.get(id=self.user.id)
        return user

    def toJSON(self):
        return json.dumps(self, default=lambda o: o.__dict__,
                          sort_keys=True, indent=4)

MyApp/Forum/forms.py
from better_profanity import profanity
from django import forms
from profanityfilter import ProfanityFilter

from Forum.models import Forum, Comment

from django.core.exceptions import ValidationError


class ForumForm(forms.ModelForm):
    class Meta:
        model = Forum
        fields = "__all__"

    def clean(self):
        cd = self.cleaned_data
        return cd


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text', 'forum', 'parent']

    def clean(self):
        cd = self.cleaned_data

        text = self.cleaned_data['text']

        # profanity-filter
        # pf = ProfanityFilter()
        # censored_text = pf.censor(text)

        # better-profanity-filter
        # TODO hate-sonar implementation or a better alternative
        profanity.load_censor_words()
        censored_text = profanity.censor(text)

        self.cleaned_data['text'] = censored_text
        return cd

MyApp/Forum/views.py
import json

from django.core import serializers
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.views import generic
from .models import Forum, Comment, Voter, User
from Forum.forms import ForumForm, CommentForm

# Geolocation
from django.contrib.gis.geos import Point
from django.contrib.gis.measure import Distance


def forum(request):
    if request.method == 'GET':
        # distance you can see posts of other people
        radius = 10
        # TODO remove hardcoded current user location

        # Position by long, lat
        college = Point(-7.9, 53.4)
        home = Point(-7.087, 53.052)
        dublin = Point(-6.27, 53.352)

        all_forums = Forum.objects.filter(location__distance_lt=(college, Distance(km=radius)))[:14][::-1]

        # TODO remove hardcoded user hardware URI and get from POST method
        # user = User.objects.get(ip="9563bb103459709e3e48019b27e1f48a")
        # previously_voted = Voter.voted.get_previously_voted(user=user)
        # not_voted = list(set(all_forums) - set(previously_voted))

        form = ForumForm
        context = {
            'forum_list': all_forums,
            'form': form
        }

        return render(request, 'Forum/index.html', context)

    if request.method == 'POST':
        form = ForumForm(request.POST, request.FILES)
        user = request.POST.get('biri_key')
        username = request.POST.get('name')

        if form.is_valid():
            try:
                user = get_object_or_404(User, biri=user)
                if username:
                    user.name = username
                    user.save()

            except Exception as f:
                user = User(biri=user)
                user.name = username
                user.save()
            lat = form.cleaned_data['latitude']
            long = form.cleaned_data['longitude']
            pnt = Point((lat, long), srid=4326)

            new_forum = form.save()
            new_forum.user = user
            new_forum.location = pnt
            new_forum.save()

            new_forum = new_forum.__dict__

            html = render_to_string('partials/_forum.html', {"forum": new_forum}, request=request)
            return HttpResponse(html)
        else:
            print(form.errors)
            return HttpResponse(status=400)


def forum_detail(request, forum_id):
    if request.method == "GET":
        forum_requested = get_object_or_404(Forum, id=forum_id)
        form = CommentForm
        comment_list = Comment.objects.filter(forum=forum_requested)
        context = {
            'forum': forum_requested,
            'comments': comment_list
        }
        return render(request, 'Forum/detail.html', context)

    if request.method == "DELETE":
        forum_requested = get_object_or_404(Forum, id=forum_id)
        key = request.GET.get('biri_key', '')
        try:
            user = get_object_or_404(User, biri=key)
            if forum_requested.user == user:
                forum_requested.user = None
                forum_requested.save()
                return HttpResponse(status=200)
            else:
                return HttpResponse(status=403)
        except Exception as f:
            print(f)


def forum_vote(request, forum_id):
    current_forum = get_object_or_404(Forum, id=forum_id)

    if request.method == 'POST':
        fingerprint = request.POST.get('fingerprint')
        vote_type = request.POST.get('vote')
        try:
            user = get_object_or_404(User, biri=fingerprint)
        except Exception as e:
            print(e)
            user = User(biri=fingerprint)
            user.save()
        try:
            voter = get_object_or_404(Voter, forum=current_forum.id, user_id=user.id)
        except Exception as f:
            print(f)
            voter = Voter(forum=current_forum.id, user=user)
            voter.save()
            current_forum.score.add(voter)

        if vote_type == "upvote":
            voter.up_vote()
        else:
            voter.down_vote()
        voter.save()
        return JsonResponse({"voter": voter.score}, status=200)

    if request.method == 'GET':
        current_score = Forum.objects.filter(id=forum_id)
        return JsonResponse({"score": current_score[0].get_score()}, status=200)

    return JsonResponse({}, status=200)


def comment(request, forum_id):
    if request.method == 'POST':
        current_forum = get_object_or_404(Forum, id=forum_id)
        form = CommentForm(request.POST)

        user = request.POST.get('biri_key')

        if form.is_valid():
            try:
                user = get_object_or_404(User, biri=user)
            except Exception as f:
                user = User(biri=user)
                user.save()

        if form.is_valid():
            new_comment = form.save()
            new_comment.user = user
            new_comment.save()
            comment_get = get_object_or_404(Comment, id=new_comment.id)

            if comment_get.parent:
                reply = True
            else:
                reply = False

            html = render_to_string('partials/_comment.html', {"comment": comment_get, "forum": current_forum,
                                                               "reply": reply},
                                    request=request)
            return HttpResponse(html)
        else:
            print(form.errors)
            return HttpResponse(status=400)

    if request.method == 'GET':
        return HttpResponse(status=404)


def comment_detail(request, forum_id, comment_id):
    if request.method == 'GET':
        found_comment = Comment.objects.filter(forum=forum_id, id=comment_id).first()
        found_comment = found_comment.__dict__
        comment_json = json.dumps(found_comment, indent=4, sort_keys=True, default=str)
        return JsonResponse({"comment": comment_json}, status=200)

    if request.method == "DELETE":
        current_comment = Comment.objects.get(id=comment_id)
        key = request.GET.get('biri_key', '')
        try:
            user = get_object_or_404(User, biri=key)
            if current_comment.user == user:
                current_comment.text = ""
                current_comment.user = None
                current_comment.save()
                return HttpResponse(status=200)
            else:
                return HttpResponse(status=403)
        except Exception as f:
            print(f)

    if request.method == "PUT":
        current_comment = Comment.objects.get(id=comment_id)
        return HttpResponse(status=204)


def comment_vote(request, forum_id, comment_id):
    current_comment = get_object_or_404(Comment, id=comment_id)

    if request.method == 'POST':
        fingerprint = request.POST.get('fingerprint')
        vote_type = request.POST.get('vote')
        try:
            user = get_object_or_404(User, biri=fingerprint)
        except Exception as e:
            print(e)
            user = User(biri=fingerprint)
            user.save()
        try:
            voter = get_object_or_404(Voter, comment=current_comment.id, user_id=user.id)
        except Exception as f:
            print(f)
            voter = Voter(comment=current_comment.id, user=user)
            voter.save()
            current_comment.score.add(voter)

        if vote_type == "upvote":
            voter.up_vote()
        else:
            voter.down_vote()
        voter.save()
        return JsonResponse({"voter": voter.score}, status=200)

    if request.method == 'GET':
        current_score = Comment.objects.filter(id=comment_id)
        return JsonResponse({"score": current_score[0].get_score()}, status=200)


def success(request):
    return HttpResponse('successfully stored')


class IndexView(generic.ListView):
    template_name = 'Forum/index.html'
    context_object_name = 'latest_forum_list'

    def get_queryset(self):
        """Return the last five published forums."""
        return Forum.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Forum
    template_name = 'Forum/detail.html'

MyApp/templates/Forum/detail.html
{% extends "template.html" %}
{% load mptt_tags %}
{% load static %}

{% block content %}
<div class="detail">
    <div class="main--image">
        <img src="{{ forum.image.url }}" alt="{{ forum.title }}">
    </div>
    <div class="main--title">
        <h1>{{ forum.title }}</h1>
        <div class="main--title-information">
            <h5>{{ forum.get_age }}</h5>
            {% if forum.user != None %}
                <h5>by {{ forum.get_user.name }}</h5>
            {% else %}
                <h5>by [Deleted]</h5>
            {% endif %}
        </div>
        <p>{{ forum.hashtag }}</p>
    </div>
    {% if forum.embed_video %}
        <div class="main--title">
            <p style="cursor:pointer" onclick="embedVideo('{{ forum.embed_video }}')">{{ forum.embed_video }} [EMBED]</p>
        </div>
    {% endif %}
    <p>{{ forum.text }}</p>
    <div id="embed_video" hidden>
    </div>
    <div class="main--title">
        <div class="forum--vote enlarge--text">
            <a role="button" title="upvote" class="clear--button" onclick="vote(this, {{ forum.id }})">
                <i class="uil uil-arrow-up"></i>
            </a>
            <div class="forum--summary--information" id="score">
                {{ forum.get_score }}
            </div>
            <a role="button" title="downvote" class="clear--button" onclick="vote(this, {{ forum.id }})">
                <i class="uil uil-arrow-down"></i>
            </a>
        </div>
        <div class="forum--summary--information enlarge--text">
            <i class="uil uil-comments-alt"></i>
            <span id="comment-count">{{ forum.comment_set.count }}</span>
        </div>
        <a role="button" class="clear--button delete--button" onclick="delete_forum()">
            <i class="uil uil-trash-alt"></i>
        </a>
        <span class="error--message--forum"></span>
    </div>
    {% if error_message %}
        <p>
            <strong>{{ error_message }}</strong>
        </p>
    {% endif %}
</div>
<div class="comment--section">
    <h1>Comments</h1>
    <form id="comment_form" action="" onsubmit="post(this);return false" method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        <input type="hidden" name="forum" value="{{ forum.id }}">
        <div class="comment--form--text">
            <label for="text">Text:</label>
            <textarea class="form--text" id="text" name="text" maxlength="2000"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">post</button>
    </form>
    <div id="comments">
        {% load mptt_tags %}
        {% recursetree comments %}
            {% include 'partials/_comment.html' with comment=node %}
            {% if not node.is_leaf_node %}
                <div class="children">
                    {{ children }}
                </div>
            {% endif %}
        {% endrecursetree %}
    </div>
</div>

<script>
function post(form) {
    let data = $(form).serializeArray();
    data.push({name: "biri_key", value: visitorId});

    $.ajax({
        url: "{% url 'Forum:comment' forum.id %}",
        data: data,
        type: 'POST',
    success: function (data) {
        const div = document.getElementById('comments');
        div.insertAdjacentHTML('afterbegin', data);

        // Remove no comments and reset form
        $("#comment_form").trigger("reset");
        $('#no_comment').remove();
        var number = parseInt($('#comment-count').text());
        $('#comment-count').text(number + 1);

        // Scroll to new comment
        $([document.documentElement, document.body]).animate({
        scrollTop: $("#comments").offset().top - 300,
            behavior:'smooth'
        }, 1500);

        },
        error: function() {
            console.log('failure');
        }
    });
}

function post_reply(form) {
    let id = "#" + form.id;
    let data = $(form).serializeArray();
    data.push({name: "biri_key", value: visitorId});

    $.ajax({
        url: "{% url 'Forum:comment' forum.id %}",
        type: 'POST',
        data: data,
        success: function (data) {
            // Insert the new comment into the thread
            let div = $(id);
            let div2 = div.closest('.comment');
            div2[0].insertAdjacentHTML('afterend', data);
            let div3 = div.closest('.comment');

            // Reset and hide the form
            $(id).trigger("reset");
            $(id).toggleClass("show_form");

            // Increment comment count
            $('#comment-count').text(parseInt($('#comment-count').text()) + 1);
        },
        error: function() {
            console.log('vote failure');
        }
    });
}

function vote(type) {
    let vote = $(type).attr("title");

    $.ajax({
    url: "{% url 'Forum:forum_vote' forum.id %}",
    data: { 'csrfmiddlewaretoken': '{{ csrf_token }}', vote: vote, fingerprint: visitorId},
    type: 'POST',
        success: function (data) {
            change_class_vote(type, '.forum--vote', data);
            fetch("{% url 'Forum:forum_vote' forum.id %}", {
                method: "GET",
                headers: {
                    "X-Requested-With": "XMLHttpRequest",
                }
                })
                .then(response => response.json())
                .then(data => {
                    $("#score").html(data['score']);
                })},
        error: function() {
            console.log('vote failure');
        }
    });
}

function comment_vote(type, comment_id) {
    let vote = $(type).attr("title");

    $.ajax({
        url: {{ forum.id }} + "/" + comment_id + "/vote",
        data: { 'csrfmiddlewaretoken' : '{{ csrf_token }}', vote: vote, fingerprint: visitorId},
        type: 'POST',
        success: function (data) {
            change_class_vote(type, '.comment--vote', data);

            fetch({{ forum.id }} + "/" + comment_id + "/vote", {
                method: "GET",
                })
                .then(response => response.json())
                .then(data => {
                    $("#comment_score_" + comment_id).html(data['score'] + " score");
                })},
        error: function() {
            console.log('vote failure')
        }
    });
}


function delete_comment(comment_id) {
    let comment = $('#comment--' + comment_id).parents('.comment');
    $.ajax({
        url: {{ forum.id }}  + "/" + comment_id + "?biri_key=" + visitorId,
        headers:{'X-CSRFToken':'{{ csrf_token }}'},
        type: 'DELETE',
        contentType: 'application/json',
        success: function(result) {
            $('.user',comment).html("<h5>[Deleted]</h5>");
            $('.comment--text', comment).html("");
            $('.comment--vote', comment).children('a').prop("onclick", null).off("click");

            },
        error: function(result){
            $('.error--message',comment).html(" [You must own this comment to delete it]");
        }
    });
}

function delete_forum() {
    $.ajax({
        url: {{ forum.id }} + "?biri_key=" + visitorId,
        headers:{'X-CSRFToken':'{{ csrf_token }}'},
        type: 'DELETE',
        contentType: 'application/json',
        success: function(result) {
            $('.main--title-information','#home').html("by [Deleted]")
            },
        error: function(result){
            $('.error--message--forum','#home').html(" [You must have created this forum to delete it]");
        }
    });
}

visitorId = ""
window.onload = (event) => {
    start();
};
</script>
{% endblock %}

MyApp/templates/Forum/index.html
{% extends "template.html" %}
{% load static %}

{% block content %}
<div class="form--heading">
    <a role="button" class="clear--button heading" id="hide">Have ideas for a Forum? Post here!</a>
</div>

<div class="main--page--form" id="form--hidden" hidden>
    <form id="forum_create" action="" method='post' enctype='multipart/form-data' novalidate>
        {% csrf_token %}
        <div class="form-information">
            <label for="title">Title:</label>
            {{ form.title }}
        </div>
        <!--
        <div class="form-information">
            <label for="hashtag">Hashtags:</label>
            {{ form.hashtag }}
        </div>
        -->
        <div class="form-information">
            <label for="text">Text:</label>
            <textarea id="text" name="text" maxlength="2000"></textarea>
        </div>
        <div class="form-information">
            <label for="name">Username:</label>
            <input id="name" name="name" maxlength="2000" placeholder="Optional"/>
        </div>
        <div class="form-information">
            <label for="image">Image:</label>
            {{ form.image }}
        </div>
        <div class="form-information">
            <label for="embed_video" >Video:</label>
            <input id="embed_video" name="embed_video" maxlength="2000" placeholder="Optional"/>
        </div>
        <input type="hidden" id="latitude" name="latitude" value="-7.9">
        <input type="hidden" id="longitude" name="longitude" value="53.4">
        <button type="submit" class="btn btn-primary form__submit">post</button>
    </form>
</div>

<div id="forums" class="home--page">
    {% if forum_list %}
        {% for forum in forum_list %}
            {% if forum %}
                {% include 'partials/_forum.html' %}
            {% endif %}
        {% endfor %}
        {% for forum in forum_list_two %}
            {% if forum %}
                {% include 'partials/_forum.html' %}
            {% endif %}
        {% endfor %}
    {% else %}
        <div id="no--forums" class="form--heading">
            <p>There have been no forums created in your area. Be the first!</p>
        </div>
    {% endif %}
</div>

<script>
let options = {
  enableHighAccuracy: true,
  timeout: 5000,
  maximumAge: 5
};

function success(pos) {
  let crd = pos.coords;

   $('#longitude').val(crd.latitude.toFixed(6));
   $('#latitude').val(crd.longitude.toFixed(6));
}

function error(err) {
  console.warn(`ERROR(${err.code}): ${err.message}`);
}

navigator.geolocation.getCurrentPosition(success, error, options);

$('#forum_create').on('submit', function(event){
    event.preventDefault();
    let form = $('#forum_create')[0];
    let data = new FormData(form);
    data.append("biri_key", visitorId);

    $.ajax({
    url: "{% url 'Forum:forum' %}",
    data: data,
    type: 'POST',
    contentType: false,
    processData: false,
    success: function (data) {
        // insert new forum at the top
        const div = document.getElementById('forums');
        div.insertAdjacentHTML('afterbegin', data);

        // reset and hide the forum form
        $("#forum_create").trigger("reset");
        $("#form--hidden").toggle();
        $("#no--forums").remove();
        },
        error: function() {
            console.log("An error occured when submitting the form");
        }
    });
});

function vote(type, id) {
    let vote = $(type).attr("title");

    $.ajax({
    url: id + "/vote",
    data: { 'csrfmiddlewaretoken' : '{{ csrf_token }}',vote: vote, fingerprint: visitorId},
    type: 'POST',
    success: function (data) {
        change_class_vote(type, '.forum--vote', data);

        fetch(id + "/vote", {
            method: "GET",
            headers: {
                "X-Requested-With": "XMLHttpRequest",
            }
            })
            .then(response => response.json())
            .then(data => {
                $("#forum--score--" + id).html(data['score']);
            })},
        error: function() {
            console.log('vote failure');
        }
    });
}

visitorId = ""
window.onload = (event) => {
    start();
};
</script>
{% endblock %}